// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.1
// source: services/attendance/attendance/v1/attendance.proto

package attendancev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AttendanceCommandService_CreateSignatureAttempt_FullMethodName = "/attendance.api.v1.AttendanceCommandService/CreateSignatureAttempt"
)

// AttendanceCommandServiceClient is the client API for AttendanceCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AttendanceCommandServiceClient interface {
	CreateSignatureAttempt(ctx context.Context, in *CreateSignatureAttemptRequest, opts ...grpc.CallOption) (*CreateSignatureAttemptResponse, error)
}

type attendanceCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAttendanceCommandServiceClient(cc grpc.ClientConnInterface) AttendanceCommandServiceClient {
	return &attendanceCommandServiceClient{cc}
}

func (c *attendanceCommandServiceClient) CreateSignatureAttempt(ctx context.Context, in *CreateSignatureAttemptRequest, opts ...grpc.CallOption) (*CreateSignatureAttemptResponse, error) {
	out := new(CreateSignatureAttemptResponse)
	err := c.cc.Invoke(ctx, AttendanceCommandService_CreateSignatureAttempt_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AttendanceCommandServiceServer is the server API for AttendanceCommandService service.
// All implementations must embed UnimplementedAttendanceCommandServiceServer
// for forward compatibility
type AttendanceCommandServiceServer interface {
	CreateSignatureAttempt(context.Context, *CreateSignatureAttemptRequest) (*CreateSignatureAttemptResponse, error)
	mustEmbedUnimplementedAttendanceCommandServiceServer()
}

// UnimplementedAttendanceCommandServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAttendanceCommandServiceServer struct {
}

func (UnimplementedAttendanceCommandServiceServer) CreateSignatureAttempt(context.Context, *CreateSignatureAttemptRequest) (*CreateSignatureAttemptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSignatureAttempt not implemented")
}
func (UnimplementedAttendanceCommandServiceServer) mustEmbedUnimplementedAttendanceCommandServiceServer() {
}

// UnsafeAttendanceCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AttendanceCommandServiceServer will
// result in compilation errors.
type UnsafeAttendanceCommandServiceServer interface {
	mustEmbedUnimplementedAttendanceCommandServiceServer()
}

func RegisterAttendanceCommandServiceServer(s grpc.ServiceRegistrar, srv AttendanceCommandServiceServer) {
	s.RegisterService(&AttendanceCommandService_ServiceDesc, srv)
}

func _AttendanceCommandService_CreateSignatureAttempt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSignatureAttemptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttendanceCommandServiceServer).CreateSignatureAttempt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttendanceCommandService_CreateSignatureAttempt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttendanceCommandServiceServer).CreateSignatureAttempt(ctx, req.(*CreateSignatureAttemptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AttendanceCommandService_ServiceDesc is the grpc.ServiceDesc for AttendanceCommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AttendanceCommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "attendance.api.v1.AttendanceCommandService",
	HandlerType: (*AttendanceCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSignatureAttempt",
			Handler:    _AttendanceCommandService_CreateSignatureAttempt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/attendance/attendance/v1/attendance.proto",
}
