// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attendance.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSignature = `-- name: CreateSignature :one
INSERT INTO signatures (
  id,
  course_id,
  signed_at,
  status,
  method,
  image_url,
  created_at,
  updated_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8
)
RETURNING id, course_id, signed_at, status, method, image_url, created_at, updated_at, deleted_at
`

type CreateSignatureParams struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	CourseID  pgtype.UUID        `db:"course_id" json:"course_id"`
	SignedAt  pgtype.Timestamptz `db:"signed_at" json:"signed_at"`
	Status    SignatureStatus    `db:"status" json:"status"`
	Method    SignatureMethod    `db:"method" json:"method"`
	ImageUrl  pgtype.Text        `db:"image_url" json:"image_url"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateSignature(ctx context.Context, arg CreateSignatureParams) (Signature, error) {
	row := q.db.QueryRow(ctx, createSignature,
		arg.ID,
		arg.CourseID,
		arg.SignedAt,
		arg.Status,
		arg.Method,
		arg.ImageUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Signature
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.SignedAt,
		&i.Status,
		&i.Method,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createStudentSignature = `-- name: CreateStudentSignature :exec
INSERT INTO student_signatures (signature_id, student_id, teacher_id, administrator_id, course_id)
VALUES ($1, $2, $3, $4, $5)
`

type CreateStudentSignatureParams struct {
	SignatureID     pgtype.UUID `db:"signature_id" json:"signature_id"`
	StudentID       pgtype.UUID `db:"student_id" json:"student_id"`
	TeacherID       pgtype.UUID `db:"teacher_id" json:"teacher_id"`
	AdministratorID pgtype.UUID `db:"administrator_id" json:"administrator_id"`
	CourseID        pgtype.UUID `db:"course_id" json:"course_id"`
}

func (q *Queries) CreateStudentSignature(ctx context.Context, arg CreateStudentSignatureParams) error {
	_, err := q.db.Exec(ctx, createStudentSignature,
		arg.SignatureID,
		arg.StudentID,
		arg.TeacherID,
		arg.AdministratorID,
		arg.CourseID,
	)
	return err
}

const createTeacherSignature = `-- name: CreateTeacherSignature :exec
INSERT INTO teacher_signatures (signature_id, teacher_id, administrator_id, course_id)
VALUES ($1, $2, $3, $4)
`

type CreateTeacherSignatureParams struct {
	SignatureID     pgtype.UUID `db:"signature_id" json:"signature_id"`
	TeacherID       pgtype.UUID `db:"teacher_id" json:"teacher_id"`
	AdministratorID pgtype.UUID `db:"administrator_id" json:"administrator_id"`
	CourseID        pgtype.UUID `db:"course_id" json:"course_id"`
}

func (q *Queries) CreateTeacherSignature(ctx context.Context, arg CreateTeacherSignatureParams) error {
	_, err := q.db.Exec(ctx, createTeacherSignature,
		arg.SignatureID,
		arg.TeacherID,
		arg.AdministratorID,
		arg.CourseID,
	)
	return err
}

const getStudentSignature = `-- name: GetStudentSignature :one
SELECT s.id,
       s.course_id,
       s.signed_at,
       s.status,
       s.method,
       s.image_url,
       s.created_at,
       s.updated_at,
       s.deleted_at,
       ss.student_id,
       ss.teacher_id,
       ss.administrator_id
FROM signatures s
INNER JOIN student_signatures ss ON ss.signature_id = s.id
WHERE s.id = $1 AND s.deleted_at IS NULL
`

type GetStudentSignatureRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	CourseID        pgtype.UUID        `db:"course_id" json:"course_id"`
	SignedAt        pgtype.Timestamptz `db:"signed_at" json:"signed_at"`
	Status          SignatureStatus    `db:"status" json:"status"`
	Method          SignatureMethod    `db:"method" json:"method"`
	ImageUrl        pgtype.Text        `db:"image_url" json:"image_url"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	StudentID       pgtype.UUID        `db:"student_id" json:"student_id"`
	TeacherID       pgtype.UUID        `db:"teacher_id" json:"teacher_id"`
	AdministratorID pgtype.UUID        `db:"administrator_id" json:"administrator_id"`
}

func (q *Queries) GetStudentSignature(ctx context.Context, id pgtype.UUID) (GetStudentSignatureRow, error) {
	row := q.db.QueryRow(ctx, getStudentSignature, id)
	var i GetStudentSignatureRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.SignedAt,
		&i.Status,
		&i.Method,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.StudentID,
		&i.TeacherID,
		&i.AdministratorID,
	)
	return i, err
}

const getTeacherSignature = `-- name: GetTeacherSignature :one
SELECT s.id,
       s.course_id,
       s.signed_at,
       s.status,
       s.method,
       s.image_url,
       s.created_at,
       s.updated_at,
       s.deleted_at,
       ts.teacher_id,
       ts.administrator_id
FROM signatures s
INNER JOIN teacher_signatures ts ON ts.signature_id = s.id
WHERE s.id = $1 AND s.deleted_at IS NULL
`

type GetTeacherSignatureRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	CourseID        pgtype.UUID        `db:"course_id" json:"course_id"`
	SignedAt        pgtype.Timestamptz `db:"signed_at" json:"signed_at"`
	Status          SignatureStatus    `db:"status" json:"status"`
	Method          SignatureMethod    `db:"method" json:"method"`
	ImageUrl        pgtype.Text        `db:"image_url" json:"image_url"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	TeacherID       pgtype.UUID        `db:"teacher_id" json:"teacher_id"`
	AdministratorID pgtype.UUID        `db:"administrator_id" json:"administrator_id"`
}

func (q *Queries) GetTeacherSignature(ctx context.Context, id pgtype.UUID) (GetTeacherSignatureRow, error) {
	row := q.db.QueryRow(ctx, getTeacherSignature, id)
	var i GetTeacherSignatureRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.SignedAt,
		&i.Status,
		&i.Method,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TeacherID,
		&i.AdministratorID,
	)
	return i, err
}

const softDeleteSignature = `-- name: SoftDeleteSignature :exec
UPDATE signatures
SET deleted_at = $2,
    updated_at = $2
WHERE id = $1 AND deleted_at IS NULL
`

type SoftDeleteSignatureParams struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

func (q *Queries) SoftDeleteSignature(ctx context.Context, arg SoftDeleteSignatureParams) error {
	_, err := q.db.Exec(ctx, softDeleteSignature, arg.ID, arg.DeletedAt)
	return err
}

const softDeleteStudentSignature = `-- name: SoftDeleteStudentSignature :exec
UPDATE student_signatures
SET deleted_at = $2
WHERE signature_id = $1 AND deleted_at IS NULL
`

type SoftDeleteStudentSignatureParams struct {
	SignatureID pgtype.UUID        `db:"signature_id" json:"signature_id"`
	DeletedAt   pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

func (q *Queries) SoftDeleteStudentSignature(ctx context.Context, arg SoftDeleteStudentSignatureParams) error {
	_, err := q.db.Exec(ctx, softDeleteStudentSignature, arg.SignatureID, arg.DeletedAt)
	return err
}

const softDeleteTeacherSignature = `-- name: SoftDeleteTeacherSignature :exec
UPDATE teacher_signatures
SET deleted_at = $2
WHERE signature_id = $1 AND deleted_at IS NULL
`

type SoftDeleteTeacherSignatureParams struct {
	SignatureID pgtype.UUID        `db:"signature_id" json:"signature_id"`
	DeletedAt   pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

func (q *Queries) SoftDeleteTeacherSignature(ctx context.Context, arg SoftDeleteTeacherSignatureParams) error {
	_, err := q.db.Exec(ctx, softDeleteTeacherSignature, arg.SignatureID, arg.DeletedAt)
	return err
}

const updateSignature = `-- name: UpdateSignature :one
UPDATE signatures
SET status = $2,
    method = $3,
    image_url = $4,
    signed_at = $5,
    updated_at = $6
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, course_id, signed_at, status, method, image_url, created_at, updated_at, deleted_at
`

type UpdateSignatureParams struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Status    SignatureStatus    `db:"status" json:"status"`
	Method    SignatureMethod    `db:"method" json:"method"`
	ImageUrl  pgtype.Text        `db:"image_url" json:"image_url"`
	SignedAt  pgtype.Timestamptz `db:"signed_at" json:"signed_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateSignature(ctx context.Context, arg UpdateSignatureParams) (Signature, error) {
	row := q.db.QueryRow(ctx, updateSignature,
		arg.ID,
		arg.Status,
		arg.Method,
		arg.ImageUrl,
		arg.SignedAt,
		arg.UpdatedAt,
	)
	var i Signature
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.SignedAt,
		&i.Status,
		&i.Method,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateStudentSignature = `-- name: UpdateStudentSignature :exec
UPDATE student_signatures
SET teacher_id = $2,
    administrator_id = $3
WHERE signature_id = $1
`

type UpdateStudentSignatureParams struct {
	SignatureID     pgtype.UUID `db:"signature_id" json:"signature_id"`
	TeacherID       pgtype.UUID `db:"teacher_id" json:"teacher_id"`
	AdministratorID pgtype.UUID `db:"administrator_id" json:"administrator_id"`
}

func (q *Queries) UpdateStudentSignature(ctx context.Context, arg UpdateStudentSignatureParams) error {
	_, err := q.db.Exec(ctx, updateStudentSignature, arg.SignatureID, arg.TeacherID, arg.AdministratorID)
	return err
}

const updateTeacherSignature = `-- name: UpdateTeacherSignature :exec
UPDATE teacher_signatures
SET administrator_id = $2
WHERE signature_id = $1
`

type UpdateTeacherSignatureParams struct {
	SignatureID     pgtype.UUID `db:"signature_id" json:"signature_id"`
	AdministratorID pgtype.UUID `db:"administrator_id" json:"administrator_id"`
}

func (q *Queries) UpdateTeacherSignature(ctx context.Context, arg UpdateTeacherSignatureParams) error {
	_, err := q.db.Exec(ctx, updateTeacherSignature, arg.SignatureID, arg.AdministratorID)
	return err
}
