// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type SignatureMethod string

const (
	SignatureMethodNfc           SignatureMethod = "nfc"
	SignatureMethodBeacon        SignatureMethod = "beacon"
	SignatureMethodBuzzLightyear SignatureMethod = "buzzLightyear"
	SignatureMethodTeacher       SignatureMethod = "teacher"
	SignatureMethodWeb           SignatureMethod = "web"
	SignatureMethodSelf          SignatureMethod = "self"
	SignatureMethodAdmin         SignatureMethod = "admin"
)

func (e *SignatureMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SignatureMethod(s)
	case string:
		*e = SignatureMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for SignatureMethod: %T", src)
	}
	return nil
}

type NullSignatureMethod struct {
	SignatureMethod SignatureMethod `json:"signature_method"`
	Valid           bool            `json:"valid"` // Valid is true if SignatureMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSignatureMethod) Scan(value interface{}) error {
	if value == nil {
		ns.SignatureMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SignatureMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSignatureMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SignatureMethod), nil
}

type SignatureStatus string

const (
	SignatureStatusPresent SignatureStatus = "present"
	SignatureStatusAbsent  SignatureStatus = "absent"
	SignatureStatusLate    SignatureStatus = "late"
	SignatureStatusExcused SignatureStatus = "excused"
	SignatureStatusInvalid SignatureStatus = "invalid"
	SignatureStatusSigned  SignatureStatus = "signed"
)

func (e *SignatureStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SignatureStatus(s)
	case string:
		*e = SignatureStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SignatureStatus: %T", src)
	}
	return nil
}

type NullSignatureStatus struct {
	SignatureStatus SignatureStatus `json:"signature_status"`
	Valid           bool            `json:"valid"` // Valid is true if SignatureStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSignatureStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SignatureStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SignatureStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSignatureStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SignatureStatus), nil
}

type Signature struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	CourseID  pgtype.UUID        `db:"course_id" json:"course_id"`
	SignedAt  pgtype.Timestamptz `db:"signed_at" json:"signed_at"`
	Status    SignatureStatus    `db:"status" json:"status"`
	Method    SignatureMethod    `db:"method" json:"method"`
	ImageUrl  pgtype.Text        `db:"image_url" json:"image_url"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type StudentSignature struct {
	SignatureID     pgtype.UUID `db:"signature_id" json:"signature_id"`
	StudentID       pgtype.UUID `db:"student_id" json:"student_id"`
	TeacherID       pgtype.UUID `db:"teacher_id" json:"teacher_id"`
	AdministratorID pgtype.UUID `db:"administrator_id" json:"administrator_id"`
	CourseID        pgtype.UUID `db:"course_id" json:"course_id"`
}

type TeacherSignature struct {
	SignatureID     pgtype.UUID `db:"signature_id" json:"signature_id"`
	TeacherID       pgtype.UUID `db:"teacher_id" json:"teacher_id"`
	CourseID        pgtype.UUID `db:"course_id" json:"course_id"`
	AdministratorID pgtype.UUID `db:"administrator_id" json:"administrator_id"`
}
