// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.4
// source: services/beacon/beacon/v1/beacon.proto

package beaconv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BeaconQueryService_ListBeaconsByClassroom_FullMethodName = "/beacon.api.v1.BeaconQueryService/ListBeaconsByClassroom"
)

// BeaconQueryServiceClient is the client API for BeaconQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BeaconQueryServiceClient interface {
	// ListBeaconsByClassroom returns all beacons assigned to a classroom.
	ListBeaconsByClassroom(ctx context.Context, in *ListBeaconsByClassroomRequest, opts ...grpc.CallOption) (*ListBeaconsByClassroomResponse, error)
}

type beaconQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBeaconQueryServiceClient(cc grpc.ClientConnInterface) BeaconQueryServiceClient {
	return &beaconQueryServiceClient{cc}
}

func (c *beaconQueryServiceClient) ListBeaconsByClassroom(ctx context.Context, in *ListBeaconsByClassroomRequest, opts ...grpc.CallOption) (*ListBeaconsByClassroomResponse, error) {
	out := new(ListBeaconsByClassroomResponse)
	err := c.cc.Invoke(ctx, BeaconQueryService_ListBeaconsByClassroom_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BeaconQueryServiceServer is the server API for BeaconQueryService service.
// All implementations must embed UnimplementedBeaconQueryServiceServer
// for forward compatibility
type BeaconQueryServiceServer interface {
	// ListBeaconsByClassroom returns all beacons assigned to a classroom.
	ListBeaconsByClassroom(context.Context, *ListBeaconsByClassroomRequest) (*ListBeaconsByClassroomResponse, error)
	mustEmbedUnimplementedBeaconQueryServiceServer()
}

// UnimplementedBeaconQueryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBeaconQueryServiceServer struct {
}

func (UnimplementedBeaconQueryServiceServer) ListBeaconsByClassroom(context.Context, *ListBeaconsByClassroomRequest) (*ListBeaconsByClassroomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBeaconsByClassroom not implemented")
}
func (UnimplementedBeaconQueryServiceServer) mustEmbedUnimplementedBeaconQueryServiceServer() {}

// UnsafeBeaconQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BeaconQueryServiceServer will
// result in compilation errors.
type UnsafeBeaconQueryServiceServer interface {
	mustEmbedUnimplementedBeaconQueryServiceServer()
}

func RegisterBeaconQueryServiceServer(s grpc.ServiceRegistrar, srv BeaconQueryServiceServer) {
	s.RegisterService(&BeaconQueryService_ServiceDesc, srv)
}

func _BeaconQueryService_ListBeaconsByClassroom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBeaconsByClassroomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconQueryServiceServer).ListBeaconsByClassroom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BeaconQueryService_ListBeaconsByClassroom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconQueryServiceServer).ListBeaconsByClassroom(ctx, req.(*ListBeaconsByClassroomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BeaconQueryService_ServiceDesc is the grpc.ServiceDesc for BeaconQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BeaconQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "beacon.api.v1.BeaconQueryService",
	HandlerType: (*BeaconQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBeaconsByClassroom",
			Handler:    _BeaconQueryService_ListBeaconsByClassroom_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/beacon/beacon/v1/beacon.proto",
}
