// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.4
// source: services/beacon/beacon/v1/beacon.proto

package beaconv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BeaconQueryService_ListBeaconsByClassroom_FullMethodName     = "/beacon.api.v1.BeaconQueryService/ListBeaconsByClassroom"
	BeaconQueryService_ValidateNfcCode_FullMethodName            = "/beacon.api.v1.BeaconQueryService/ValidateNfcCode"
	BeaconQueryService_ValidateBuzzLightyearProof_FullMethodName = "/beacon.api.v1.BeaconQueryService/ValidateBuzzLightyearProof"
	BeaconQueryService_GetNfcCode_FullMethodName                 = "/beacon.api.v1.BeaconQueryService/GetNfcCode"
)

// BeaconQueryServiceClient is the client API for BeaconQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BeaconQueryServiceClient interface {
	// ListBeaconsByClassroom returns all beacons assigned to a classroom.
	ListBeaconsByClassroom(ctx context.Context, in *ListBeaconsByClassroomRequest, opts ...grpc.CallOption) (*ListBeaconsByClassroomResponse, error)
	// ValidateNfcCode validates a TOTP code emitted by a beacon.
	ValidateNfcCode(ctx context.Context, in *ValidateNfcCodeRequest, opts ...grpc.CallOption) (*ValidateNfcCodeResponse, error)
	// ValidateBuzzLightyearProof validates a beacon-signed BuzzLightyear code.
	ValidateBuzzLightyearProof(ctx context.Context, in *ValidateBuzzLightyearProofRequest, opts ...grpc.CallOption) (*ValidateBuzzLightyearProofResponse, error)
	// GetNfcCode returns the current TOTP code for a beacon (debug only).
	GetNfcCode(ctx context.Context, in *GetNfcCodeRequest, opts ...grpc.CallOption) (*GetNfcCodeResponse, error)
}

type beaconQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBeaconQueryServiceClient(cc grpc.ClientConnInterface) BeaconQueryServiceClient {
	return &beaconQueryServiceClient{cc}
}

func (c *beaconQueryServiceClient) ListBeaconsByClassroom(ctx context.Context, in *ListBeaconsByClassroomRequest, opts ...grpc.CallOption) (*ListBeaconsByClassroomResponse, error) {
	out := new(ListBeaconsByClassroomResponse)
	err := c.cc.Invoke(ctx, BeaconQueryService_ListBeaconsByClassroom_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconQueryServiceClient) ValidateNfcCode(ctx context.Context, in *ValidateNfcCodeRequest, opts ...grpc.CallOption) (*ValidateNfcCodeResponse, error) {
	out := new(ValidateNfcCodeResponse)
	err := c.cc.Invoke(ctx, BeaconQueryService_ValidateNfcCode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconQueryServiceClient) ValidateBuzzLightyearProof(ctx context.Context, in *ValidateBuzzLightyearProofRequest, opts ...grpc.CallOption) (*ValidateBuzzLightyearProofResponse, error) {
	out := new(ValidateBuzzLightyearProofResponse)
	err := c.cc.Invoke(ctx, BeaconQueryService_ValidateBuzzLightyearProof_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconQueryServiceClient) GetNfcCode(ctx context.Context, in *GetNfcCodeRequest, opts ...grpc.CallOption) (*GetNfcCodeResponse, error) {
	out := new(GetNfcCodeResponse)
	err := c.cc.Invoke(ctx, BeaconQueryService_GetNfcCode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BeaconQueryServiceServer is the server API for BeaconQueryService service.
// All implementations must embed UnimplementedBeaconQueryServiceServer
// for forward compatibility
type BeaconQueryServiceServer interface {
	// ListBeaconsByClassroom returns all beacons assigned to a classroom.
	ListBeaconsByClassroom(context.Context, *ListBeaconsByClassroomRequest) (*ListBeaconsByClassroomResponse, error)
	// ValidateNfcCode validates a TOTP code emitted by a beacon.
	ValidateNfcCode(context.Context, *ValidateNfcCodeRequest) (*ValidateNfcCodeResponse, error)
	// ValidateBuzzLightyearProof validates a beacon-signed BuzzLightyear code.
	ValidateBuzzLightyearProof(context.Context, *ValidateBuzzLightyearProofRequest) (*ValidateBuzzLightyearProofResponse, error)
	// GetNfcCode returns the current TOTP code for a beacon (debug only).
	GetNfcCode(context.Context, *GetNfcCodeRequest) (*GetNfcCodeResponse, error)
	mustEmbedUnimplementedBeaconQueryServiceServer()
}

// UnimplementedBeaconQueryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBeaconQueryServiceServer struct {
}

func (UnimplementedBeaconQueryServiceServer) ListBeaconsByClassroom(context.Context, *ListBeaconsByClassroomRequest) (*ListBeaconsByClassroomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBeaconsByClassroom not implemented")
}
func (UnimplementedBeaconQueryServiceServer) ValidateNfcCode(context.Context, *ValidateNfcCodeRequest) (*ValidateNfcCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateNfcCode not implemented")
}
func (UnimplementedBeaconQueryServiceServer) ValidateBuzzLightyearProof(context.Context, *ValidateBuzzLightyearProofRequest) (*ValidateBuzzLightyearProofResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateBuzzLightyearProof not implemented")
}
func (UnimplementedBeaconQueryServiceServer) GetNfcCode(context.Context, *GetNfcCodeRequest) (*GetNfcCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNfcCode not implemented")
}
func (UnimplementedBeaconQueryServiceServer) mustEmbedUnimplementedBeaconQueryServiceServer() {}

// UnsafeBeaconQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BeaconQueryServiceServer will
// result in compilation errors.
type UnsafeBeaconQueryServiceServer interface {
	mustEmbedUnimplementedBeaconQueryServiceServer()
}

func RegisterBeaconQueryServiceServer(s grpc.ServiceRegistrar, srv BeaconQueryServiceServer) {
	s.RegisterService(&BeaconQueryService_ServiceDesc, srv)
}

func _BeaconQueryService_ListBeaconsByClassroom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBeaconsByClassroomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconQueryServiceServer).ListBeaconsByClassroom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BeaconQueryService_ListBeaconsByClassroom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconQueryServiceServer).ListBeaconsByClassroom(ctx, req.(*ListBeaconsByClassroomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconQueryService_ValidateNfcCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateNfcCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconQueryServiceServer).ValidateNfcCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BeaconQueryService_ValidateNfcCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconQueryServiceServer).ValidateNfcCode(ctx, req.(*ValidateNfcCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconQueryService_ValidateBuzzLightyearProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateBuzzLightyearProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconQueryServiceServer).ValidateBuzzLightyearProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BeaconQueryService_ValidateBuzzLightyearProof_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconQueryServiceServer).ValidateBuzzLightyearProof(ctx, req.(*ValidateBuzzLightyearProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconQueryService_GetNfcCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNfcCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconQueryServiceServer).GetNfcCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BeaconQueryService_GetNfcCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconQueryServiceServer).GetNfcCode(ctx, req.(*GetNfcCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BeaconQueryService_ServiceDesc is the grpc.ServiceDesc for BeaconQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BeaconQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "beacon.api.v1.BeaconQueryService",
	HandlerType: (*BeaconQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBeaconsByClassroom",
			Handler:    _BeaconQueryService_ListBeaconsByClassroom_Handler,
		},
		{
			MethodName: "ValidateNfcCode",
			Handler:    _BeaconQueryService_ValidateNfcCode_Handler,
		},
		{
			MethodName: "ValidateBuzzLightyearProof",
			Handler:    _BeaconQueryService_ValidateBuzzLightyearProof_Handler,
		},
		{
			MethodName: "GetNfcCode",
			Handler:    _BeaconQueryService_GetNfcCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/beacon/beacon/v1/beacon.proto",
}

const (
	BeaconCommandService_AssignBeaconToClassroom_FullMethodName   = "/beacon.api.v1.BeaconCommandService/AssignBeaconToClassroom"
	BeaconCommandService_RemoveBeaconFromClassroom_FullMethodName = "/beacon.api.v1.BeaconCommandService/RemoveBeaconFromClassroom"
)

// BeaconCommandServiceClient is the client API for BeaconCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BeaconCommandServiceClient interface {
	// AssignBeaconToClassroom assigns a beacon to a classroom.
	AssignBeaconToClassroom(ctx context.Context, in *AssignBeaconToClassroomRequest, opts ...grpc.CallOption) (*AssignBeaconToClassroomResponse, error)
	// RemoveBeaconFromClassroom removes a beacon from a classroom.
	RemoveBeaconFromClassroom(ctx context.Context, in *RemoveBeaconFromClassroomRequest, opts ...grpc.CallOption) (*RemoveBeaconFromClassroomResponse, error)
}

type beaconCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBeaconCommandServiceClient(cc grpc.ClientConnInterface) BeaconCommandServiceClient {
	return &beaconCommandServiceClient{cc}
}

func (c *beaconCommandServiceClient) AssignBeaconToClassroom(ctx context.Context, in *AssignBeaconToClassroomRequest, opts ...grpc.CallOption) (*AssignBeaconToClassroomResponse, error) {
	out := new(AssignBeaconToClassroomResponse)
	err := c.cc.Invoke(ctx, BeaconCommandService_AssignBeaconToClassroom_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconCommandServiceClient) RemoveBeaconFromClassroom(ctx context.Context, in *RemoveBeaconFromClassroomRequest, opts ...grpc.CallOption) (*RemoveBeaconFromClassroomResponse, error) {
	out := new(RemoveBeaconFromClassroomResponse)
	err := c.cc.Invoke(ctx, BeaconCommandService_RemoveBeaconFromClassroom_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BeaconCommandServiceServer is the server API for BeaconCommandService service.
// All implementations must embed UnimplementedBeaconCommandServiceServer
// for forward compatibility
type BeaconCommandServiceServer interface {
	// AssignBeaconToClassroom assigns a beacon to a classroom.
	AssignBeaconToClassroom(context.Context, *AssignBeaconToClassroomRequest) (*AssignBeaconToClassroomResponse, error)
	// RemoveBeaconFromClassroom removes a beacon from a classroom.
	RemoveBeaconFromClassroom(context.Context, *RemoveBeaconFromClassroomRequest) (*RemoveBeaconFromClassroomResponse, error)
	mustEmbedUnimplementedBeaconCommandServiceServer()
}

// UnimplementedBeaconCommandServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBeaconCommandServiceServer struct {
}

func (UnimplementedBeaconCommandServiceServer) AssignBeaconToClassroom(context.Context, *AssignBeaconToClassroomRequest) (*AssignBeaconToClassroomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignBeaconToClassroom not implemented")
}
func (UnimplementedBeaconCommandServiceServer) RemoveBeaconFromClassroom(context.Context, *RemoveBeaconFromClassroomRequest) (*RemoveBeaconFromClassroomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveBeaconFromClassroom not implemented")
}
func (UnimplementedBeaconCommandServiceServer) mustEmbedUnimplementedBeaconCommandServiceServer() {}

// UnsafeBeaconCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BeaconCommandServiceServer will
// result in compilation errors.
type UnsafeBeaconCommandServiceServer interface {
	mustEmbedUnimplementedBeaconCommandServiceServer()
}

func RegisterBeaconCommandServiceServer(s grpc.ServiceRegistrar, srv BeaconCommandServiceServer) {
	s.RegisterService(&BeaconCommandService_ServiceDesc, srv)
}

func _BeaconCommandService_AssignBeaconToClassroom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignBeaconToClassroomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconCommandServiceServer).AssignBeaconToClassroom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BeaconCommandService_AssignBeaconToClassroom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconCommandServiceServer).AssignBeaconToClassroom(ctx, req.(*AssignBeaconToClassroomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconCommandService_RemoveBeaconFromClassroom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveBeaconFromClassroomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconCommandServiceServer).RemoveBeaconFromClassroom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BeaconCommandService_RemoveBeaconFromClassroom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconCommandServiceServer).RemoveBeaconFromClassroom(ctx, req.(*RemoveBeaconFromClassroomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BeaconCommandService_ServiceDesc is the grpc.ServiceDesc for BeaconCommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BeaconCommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "beacon.api.v1.BeaconCommandService",
	HandlerType: (*BeaconCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssignBeaconToClassroom",
			Handler:    _BeaconCommandService_AssignBeaconToClassroom_Handler,
		},
		{
			MethodName: "RemoveBeaconFromClassroom",
			Handler:    _BeaconCommandService_RemoveBeaconFromClassroom_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/beacon/beacon/v1/beacon.proto",
}
