// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.33.4
// source: services/beacon/beacon/v1/beacon.proto

package beaconv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Beacon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SerialNumber   int64  `protobuf:"varint,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	ClassroomId    string `protobuf:"bytes,3,opt,name=classroom_id,json=classroomId,proto3" json:"classroom_id,omitempty"`
	ProgramVersion string `protobuf:"bytes,4,opt,name=program_version,json=programVersion,proto3" json:"program_version,omitempty"`
}

func (x *Beacon) Reset() {
	*x = Beacon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_beacon_beacon_v1_beacon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Beacon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Beacon) ProtoMessage() {}

func (x *Beacon) ProtoReflect() protoreflect.Message {
	mi := &file_services_beacon_beacon_v1_beacon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Beacon.ProtoReflect.Descriptor instead.
func (*Beacon) Descriptor() ([]byte, []int) {
	return file_services_beacon_beacon_v1_beacon_proto_rawDescGZIP(), []int{0}
}

func (x *Beacon) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Beacon) GetSerialNumber() int64 {
	if x != nil {
		return x.SerialNumber
	}
	return 0
}

func (x *Beacon) GetClassroomId() string {
	if x != nil {
		return x.ClassroomId
	}
	return ""
}

func (x *Beacon) GetProgramVersion() string {
	if x != nil {
		return x.ProgramVersion
	}
	return ""
}

type ListBeaconsByClassroomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClassroomId string `protobuf:"bytes,1,opt,name=classroom_id,json=classroomId,proto3" json:"classroom_id,omitempty"`
}

func (x *ListBeaconsByClassroomRequest) Reset() {
	*x = ListBeaconsByClassroomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_beacon_beacon_v1_beacon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBeaconsByClassroomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBeaconsByClassroomRequest) ProtoMessage() {}

func (x *ListBeaconsByClassroomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_beacon_beacon_v1_beacon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBeaconsByClassroomRequest.ProtoReflect.Descriptor instead.
func (*ListBeaconsByClassroomRequest) Descriptor() ([]byte, []int) {
	return file_services_beacon_beacon_v1_beacon_proto_rawDescGZIP(), []int{1}
}

func (x *ListBeaconsByClassroomRequest) GetClassroomId() string {
	if x != nil {
		return x.ClassroomId
	}
	return ""
}

type ListBeaconsByClassroomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Beacons []*Beacon `protobuf:"bytes,1,rep,name=beacons,proto3" json:"beacons,omitempty"`
}

func (x *ListBeaconsByClassroomResponse) Reset() {
	*x = ListBeaconsByClassroomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_beacon_beacon_v1_beacon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBeaconsByClassroomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBeaconsByClassroomResponse) ProtoMessage() {}

func (x *ListBeaconsByClassroomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_beacon_beacon_v1_beacon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBeaconsByClassroomResponse.ProtoReflect.Descriptor instead.
func (*ListBeaconsByClassroomResponse) Descriptor() ([]byte, []int) {
	return file_services_beacon_beacon_v1_beacon_proto_rawDescGZIP(), []int{2}
}

func (x *ListBeaconsByClassroomResponse) GetBeacons() []*Beacon {
	if x != nil {
		return x.Beacons
	}
	return nil
}

type AssignBeaconToClassroomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BeaconId    string `protobuf:"bytes,1,opt,name=beacon_id,json=beaconId,proto3" json:"beacon_id,omitempty"`
	ClassroomId string `protobuf:"bytes,2,opt,name=classroom_id,json=classroomId,proto3" json:"classroom_id,omitempty"`
}

func (x *AssignBeaconToClassroomRequest) Reset() {
	*x = AssignBeaconToClassroomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_beacon_beacon_v1_beacon_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignBeaconToClassroomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignBeaconToClassroomRequest) ProtoMessage() {}

func (x *AssignBeaconToClassroomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_beacon_beacon_v1_beacon_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignBeaconToClassroomRequest.ProtoReflect.Descriptor instead.
func (*AssignBeaconToClassroomRequest) Descriptor() ([]byte, []int) {
	return file_services_beacon_beacon_v1_beacon_proto_rawDescGZIP(), []int{3}
}

func (x *AssignBeaconToClassroomRequest) GetBeaconId() string {
	if x != nil {
		return x.BeaconId
	}
	return ""
}

func (x *AssignBeaconToClassroomRequest) GetClassroomId() string {
	if x != nil {
		return x.ClassroomId
	}
	return ""
}

type AssignBeaconToClassroomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AssignBeaconToClassroomResponse) Reset() {
	*x = AssignBeaconToClassroomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_beacon_beacon_v1_beacon_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignBeaconToClassroomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignBeaconToClassroomResponse) ProtoMessage() {}

func (x *AssignBeaconToClassroomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_beacon_beacon_v1_beacon_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignBeaconToClassroomResponse.ProtoReflect.Descriptor instead.
func (*AssignBeaconToClassroomResponse) Descriptor() ([]byte, []int) {
	return file_services_beacon_beacon_v1_beacon_proto_rawDescGZIP(), []int{4}
}

type RemoveBeaconFromClassroomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BeaconId    string `protobuf:"bytes,1,opt,name=beacon_id,json=beaconId,proto3" json:"beacon_id,omitempty"`
	ClassroomId string `protobuf:"bytes,2,opt,name=classroom_id,json=classroomId,proto3" json:"classroom_id,omitempty"`
}

func (x *RemoveBeaconFromClassroomRequest) Reset() {
	*x = RemoveBeaconFromClassroomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_beacon_beacon_v1_beacon_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveBeaconFromClassroomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBeaconFromClassroomRequest) ProtoMessage() {}

func (x *RemoveBeaconFromClassroomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_beacon_beacon_v1_beacon_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBeaconFromClassroomRequest.ProtoReflect.Descriptor instead.
func (*RemoveBeaconFromClassroomRequest) Descriptor() ([]byte, []int) {
	return file_services_beacon_beacon_v1_beacon_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveBeaconFromClassroomRequest) GetBeaconId() string {
	if x != nil {
		return x.BeaconId
	}
	return ""
}

func (x *RemoveBeaconFromClassroomRequest) GetClassroomId() string {
	if x != nil {
		return x.ClassroomId
	}
	return ""
}

type RemoveBeaconFromClassroomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveBeaconFromClassroomResponse) Reset() {
	*x = RemoveBeaconFromClassroomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_beacon_beacon_v1_beacon_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveBeaconFromClassroomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBeaconFromClassroomResponse) ProtoMessage() {}

func (x *RemoveBeaconFromClassroomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_beacon_beacon_v1_beacon_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBeaconFromClassroomResponse.ProtoReflect.Descriptor instead.
func (*RemoveBeaconFromClassroomResponse) Descriptor() ([]byte, []int) {
	return file_services_beacon_beacon_v1_beacon_proto_rawDescGZIP(), []int{6}
}

type ValidateNfcCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BeaconId string `protobuf:"bytes,1,opt,name=beacon_id,json=beaconId,proto3" json:"beacon_id,omitempty"`
	TotpCode string `protobuf:"bytes,2,opt,name=totp_code,json=totpCode,proto3" json:"totp_code,omitempty"`
}

func (x *ValidateNfcCodeRequest) Reset() {
	*x = ValidateNfcCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_beacon_beacon_v1_beacon_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateNfcCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateNfcCodeRequest) ProtoMessage() {}

func (x *ValidateNfcCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_beacon_beacon_v1_beacon_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateNfcCodeRequest.ProtoReflect.Descriptor instead.
func (*ValidateNfcCodeRequest) Descriptor() ([]byte, []int) {
	return file_services_beacon_beacon_v1_beacon_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateNfcCodeRequest) GetBeaconId() string {
	if x != nil {
		return x.BeaconId
	}
	return ""
}

func (x *ValidateNfcCodeRequest) GetTotpCode() string {
	if x != nil {
		return x.TotpCode
	}
	return ""
}

type ValidateNfcCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsValid     bool   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	ClassroomId string `protobuf:"bytes,2,opt,name=classroom_id,json=classroomId,proto3" json:"classroom_id,omitempty"`
	ErrorCode   string `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
}

func (x *ValidateNfcCodeResponse) Reset() {
	*x = ValidateNfcCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_beacon_beacon_v1_beacon_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateNfcCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateNfcCodeResponse) ProtoMessage() {}

func (x *ValidateNfcCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_beacon_beacon_v1_beacon_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateNfcCodeResponse.ProtoReflect.Descriptor instead.
func (*ValidateNfcCodeResponse) Descriptor() ([]byte, []int) {
	return file_services_beacon_beacon_v1_beacon_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateNfcCodeResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ValidateNfcCodeResponse) GetClassroomId() string {
	if x != nil {
		return x.ClassroomId
	}
	return ""
}

func (x *ValidateNfcCodeResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type ValidateBuzzLightyearProofRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BeaconId  string `protobuf:"bytes,1,opt,name=beacon_id,json=beaconId,proto3" json:"beacon_id,omitempty"`
	Code      int32  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Signature string `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	StudentId string `protobuf:"bytes,4,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
}

func (x *ValidateBuzzLightyearProofRequest) Reset() {
	*x = ValidateBuzzLightyearProofRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_beacon_beacon_v1_beacon_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateBuzzLightyearProofRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateBuzzLightyearProofRequest) ProtoMessage() {}

func (x *ValidateBuzzLightyearProofRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_beacon_beacon_v1_beacon_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateBuzzLightyearProofRequest.ProtoReflect.Descriptor instead.
func (*ValidateBuzzLightyearProofRequest) Descriptor() ([]byte, []int) {
	return file_services_beacon_beacon_v1_beacon_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateBuzzLightyearProofRequest) GetBeaconId() string {
	if x != nil {
		return x.BeaconId
	}
	return ""
}

func (x *ValidateBuzzLightyearProofRequest) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ValidateBuzzLightyearProofRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *ValidateBuzzLightyearProofRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type ValidateBuzzLightyearProofResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsValid     bool   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	ErrorCode   string `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ClassroomId string `protobuf:"bytes,3,opt,name=classroom_id,json=classroomId,proto3" json:"classroom_id,omitempty"`
}

func (x *ValidateBuzzLightyearProofResponse) Reset() {
	*x = ValidateBuzzLightyearProofResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_beacon_beacon_v1_beacon_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateBuzzLightyearProofResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateBuzzLightyearProofResponse) ProtoMessage() {}

func (x *ValidateBuzzLightyearProofResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_beacon_beacon_v1_beacon_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateBuzzLightyearProofResponse.ProtoReflect.Descriptor instead.
func (*ValidateBuzzLightyearProofResponse) Descriptor() ([]byte, []int) {
	return file_services_beacon_beacon_v1_beacon_proto_rawDescGZIP(), []int{10}
}

func (x *ValidateBuzzLightyearProofResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ValidateBuzzLightyearProofResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ValidateBuzzLightyearProofResponse) GetClassroomId() string {
	if x != nil {
		return x.ClassroomId
	}
	return ""
}

type GetNfcCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BeaconId string `protobuf:"bytes,1,opt,name=beacon_id,json=beaconId,proto3" json:"beacon_id,omitempty"`
}

func (x *GetNfcCodeRequest) Reset() {
	*x = GetNfcCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_beacon_beacon_v1_beacon_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNfcCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNfcCodeRequest) ProtoMessage() {}

func (x *GetNfcCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_beacon_beacon_v1_beacon_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNfcCodeRequest.ProtoReflect.Descriptor instead.
func (*GetNfcCodeRequest) Descriptor() ([]byte, []int) {
	return file_services_beacon_beacon_v1_beacon_proto_rawDescGZIP(), []int{11}
}

func (x *GetNfcCodeRequest) GetBeaconId() string {
	if x != nil {
		return x.BeaconId
	}
	return ""
}

type GetNfcCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotpCode    string `protobuf:"bytes,1,opt,name=totp_code,json=totpCode,proto3" json:"totp_code,omitempty"`
	GeneratedAt int64  `protobuf:"varint,2,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	// Debug-only fingerprint of the decoded TOTP secret.
	SecretFingerprint string `protobuf:"bytes,3,opt,name=secret_fingerprint,json=secretFingerprint,proto3" json:"secret_fingerprint,omitempty"`
}

func (x *GetNfcCodeResponse) Reset() {
	*x = GetNfcCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_beacon_beacon_v1_beacon_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNfcCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNfcCodeResponse) ProtoMessage() {}

func (x *GetNfcCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_beacon_beacon_v1_beacon_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNfcCodeResponse.ProtoReflect.Descriptor instead.
func (*GetNfcCodeResponse) Descriptor() ([]byte, []int) {
	return file_services_beacon_beacon_v1_beacon_proto_rawDescGZIP(), []int{12}
}

func (x *GetNfcCodeResponse) GetTotpCode() string {
	if x != nil {
		return x.TotpCode
	}
	return ""
}

func (x *GetNfcCodeResponse) GetGeneratedAt() int64 {
	if x != nil {
		return x.GeneratedAt
	}
	return 0
}

func (x *GetNfcCodeResponse) GetSecretFingerprint() string {
	if x != nil {
		return x.SecretFingerprint
	}
	return ""
}

var File_services_beacon_beacon_v1_beacon_proto protoreflect.FileDescriptor

var file_services_beacon_beacon_v1_beacon_proto_rawDesc = []byte{
	0x0a, 0x26, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x62, 0x65, 0x61, 0x63, 0x6f,
	0x6e, 0x2f, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x65, 0x61, 0x63,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x22, 0x89, 0x01, 0x0a, 0x06, 0x42, 0x65, 0x61, 0x63,
	0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x5f, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6c, 0x61, 0x73, 0x73,
	0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63,
	0x6c, 0x61, 0x73, 0x73, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x70, 0x72,
	0x6f, 0x67, 0x72, 0x61, 0x6d, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x22, 0x42, 0x0a, 0x1d, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x65, 0x61, 0x63, 0x6f,
	0x6e, 0x73, 0x42, 0x79, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x72, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x72, 0x6f, 0x6f,
	0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6c, 0x61, 0x73,
	0x73, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x51, 0x0a, 0x1e, 0x4c, 0x69, 0x73, 0x74, 0x42,
	0x65, 0x61, 0x63, 0x6f, 0x6e, 0x73, 0x42, 0x79, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x72, 0x6f, 0x6f,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x07, 0x62, 0x65, 0x61,
	0x63, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x62, 0x65, 0x61,
	0x63, 0x6f, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x65, 0x61, 0x63, 0x6f,
	0x6e, 0x52, 0x07, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x73, 0x22, 0x60, 0x0a, 0x1e, 0x41, 0x73,
	0x73, 0x69, 0x67, 0x6e, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x54, 0x6f, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x72, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6c, 0x61,
	0x73, 0x73, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x21, 0x0a, 0x1f,
	0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x54, 0x6f, 0x43, 0x6c,
	0x61, 0x73, 0x73, 0x72, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x62, 0x0a, 0x20, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x46,
	0x72, 0x6f, 0x6d, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x72, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x49, 0x64,
	0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x72, 0x6f, 0x6f,
	0x6d, 0x49, 0x64, 0x22, 0x23, 0x0a, 0x21, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x42, 0x65, 0x61,
	0x63, 0x6f, 0x6e, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x72, 0x6f, 0x6f, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x52, 0x0a, 0x16, 0x56, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x4e, 0x66, 0x63, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x74, 0x6f, 0x74, 0x70, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x74, 0x6f, 0x74, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x76, 0x0a, 0x17,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x66, 0x63, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x72, 0x6f, 0x6f, 0x6d, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x72,
	0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x22, 0x91, 0x01, 0x0a, 0x21, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x42, 0x75, 0x7a, 0x7a, 0x4c, 0x69, 0x67, 0x68, 0x74, 0x79, 0x65, 0x61, 0x72, 0x50, 0x72,
	0x6f, 0x6f, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x65,
	0x61, 0x63, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62,
	0x65, 0x61, 0x63, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x75,
	0x64, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x81, 0x01, 0x0a, 0x22, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x42, 0x75, 0x7a, 0x7a, 0x4c, 0x69, 0x67, 0x68, 0x74, 0x79, 0x65,
	0x61, 0x72, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x69, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6c, 0x61,
	0x73, 0x73, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x30, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x4e, 0x66, 0x63, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x83,
	0x01, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4e, 0x66, 0x63, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x6f, 0x74, 0x70, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x6f, 0x74, 0x70, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x2d, 0x0a, 0x12, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f,
	0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x11, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70,
	0x72, 0x69, 0x6e, 0x74, 0x32, 0xc4, 0x03, 0x0a, 0x12, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x75, 0x0a, 0x16, 0x4c,
	0x69, 0x73, 0x74, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x73, 0x42, 0x79, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x72, 0x6f, 0x6f, 0x6d, 0x12, 0x2c, 0x2e, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e,
	0x73, 0x42, 0x79, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x72, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x73, 0x42,
	0x79, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x72, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x60, 0x0a, 0x0f, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x66,
	0x63, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x25, 0x2e, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x66,
	0x63, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x62,
	0x65, 0x61, 0x63, 0x6f, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x66, 0x63, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x81, 0x01, 0x0a, 0x1a, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x42, 0x75, 0x7a, 0x7a, 0x4c, 0x69, 0x67, 0x68, 0x74, 0x79, 0x65, 0x61, 0x72, 0x50, 0x72,
	0x6f, 0x6f, 0x66, 0x12, 0x30, 0x2e, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x42, 0x75, 0x7a, 0x7a,
	0x4c, 0x69, 0x67, 0x68, 0x74, 0x79, 0x65, 0x61, 0x72, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x42, 0x75,
	0x7a, 0x7a, 0x4c, 0x69, 0x67, 0x68, 0x74, 0x79, 0x65, 0x61, 0x72, 0x50, 0x72, 0x6f, 0x6f, 0x66,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4e,
	0x66, 0x63, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x2e, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x66, 0x63, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x62, 0x65, 0x61, 0x63, 0x6f,
	0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x66, 0x63, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x90, 0x02, 0x0a, 0x14,
	0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x78, 0x0a, 0x17, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x42, 0x65,
	0x61, 0x63, 0x6f, 0x6e, 0x54, 0x6f, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x72, 0x6f, 0x6f, 0x6d, 0x12,
	0x2d, 0x2e, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x54, 0x6f, 0x43, 0x6c,
	0x61, 0x73, 0x73, 0x72, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e,
	0x2e, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x41,
	0x73, 0x73, 0x69, 0x67, 0x6e, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x54, 0x6f, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x72, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x7e,
	0x0a, 0x19, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x46, 0x72,
	0x6f, 0x6d, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x72, 0x6f, 0x6f, 0x6d, 0x12, 0x2f, 0x2e, 0x62, 0x65,
	0x61, 0x63, 0x6f, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x72, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e, 0x62,
	0x65, 0x61, 0x63, 0x6f, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x72, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x25,
	0x5a, 0x23, 0x73, 0x65, 0x6d, 0x61, 0x70, 0x68, 0x6f, 0x72, 0x65, 0x2f, 0x62, 0x65, 0x61, 0x63,
	0x6f, 0x6e, 0x2f, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x62, 0x65, 0x61,
	0x63, 0x6f, 0x6e, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_beacon_beacon_v1_beacon_proto_rawDescOnce sync.Once
	file_services_beacon_beacon_v1_beacon_proto_rawDescData = file_services_beacon_beacon_v1_beacon_proto_rawDesc
)

func file_services_beacon_beacon_v1_beacon_proto_rawDescGZIP() []byte {
	file_services_beacon_beacon_v1_beacon_proto_rawDescOnce.Do(func() {
		file_services_beacon_beacon_v1_beacon_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_beacon_beacon_v1_beacon_proto_rawDescData)
	})
	return file_services_beacon_beacon_v1_beacon_proto_rawDescData
}

var file_services_beacon_beacon_v1_beacon_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_services_beacon_beacon_v1_beacon_proto_goTypes = []interface{}{
	(*Beacon)(nil),                             // 0: beacon.api.v1.Beacon
	(*ListBeaconsByClassroomRequest)(nil),      // 1: beacon.api.v1.ListBeaconsByClassroomRequest
	(*ListBeaconsByClassroomResponse)(nil),     // 2: beacon.api.v1.ListBeaconsByClassroomResponse
	(*AssignBeaconToClassroomRequest)(nil),     // 3: beacon.api.v1.AssignBeaconToClassroomRequest
	(*AssignBeaconToClassroomResponse)(nil),    // 4: beacon.api.v1.AssignBeaconToClassroomResponse
	(*RemoveBeaconFromClassroomRequest)(nil),   // 5: beacon.api.v1.RemoveBeaconFromClassroomRequest
	(*RemoveBeaconFromClassroomResponse)(nil),  // 6: beacon.api.v1.RemoveBeaconFromClassroomResponse
	(*ValidateNfcCodeRequest)(nil),             // 7: beacon.api.v1.ValidateNfcCodeRequest
	(*ValidateNfcCodeResponse)(nil),            // 8: beacon.api.v1.ValidateNfcCodeResponse
	(*ValidateBuzzLightyearProofRequest)(nil),  // 9: beacon.api.v1.ValidateBuzzLightyearProofRequest
	(*ValidateBuzzLightyearProofResponse)(nil), // 10: beacon.api.v1.ValidateBuzzLightyearProofResponse
	(*GetNfcCodeRequest)(nil),                  // 11: beacon.api.v1.GetNfcCodeRequest
	(*GetNfcCodeResponse)(nil),                 // 12: beacon.api.v1.GetNfcCodeResponse
}
var file_services_beacon_beacon_v1_beacon_proto_depIdxs = []int32{
	0,  // 0: beacon.api.v1.ListBeaconsByClassroomResponse.beacons:type_name -> beacon.api.v1.Beacon
	1,  // 1: beacon.api.v1.BeaconQueryService.ListBeaconsByClassroom:input_type -> beacon.api.v1.ListBeaconsByClassroomRequest
	7,  // 2: beacon.api.v1.BeaconQueryService.ValidateNfcCode:input_type -> beacon.api.v1.ValidateNfcCodeRequest
	9,  // 3: beacon.api.v1.BeaconQueryService.ValidateBuzzLightyearProof:input_type -> beacon.api.v1.ValidateBuzzLightyearProofRequest
	11, // 4: beacon.api.v1.BeaconQueryService.GetNfcCode:input_type -> beacon.api.v1.GetNfcCodeRequest
	3,  // 5: beacon.api.v1.BeaconCommandService.AssignBeaconToClassroom:input_type -> beacon.api.v1.AssignBeaconToClassroomRequest
	5,  // 6: beacon.api.v1.BeaconCommandService.RemoveBeaconFromClassroom:input_type -> beacon.api.v1.RemoveBeaconFromClassroomRequest
	2,  // 7: beacon.api.v1.BeaconQueryService.ListBeaconsByClassroom:output_type -> beacon.api.v1.ListBeaconsByClassroomResponse
	8,  // 8: beacon.api.v1.BeaconQueryService.ValidateNfcCode:output_type -> beacon.api.v1.ValidateNfcCodeResponse
	10, // 9: beacon.api.v1.BeaconQueryService.ValidateBuzzLightyearProof:output_type -> beacon.api.v1.ValidateBuzzLightyearProofResponse
	12, // 10: beacon.api.v1.BeaconQueryService.GetNfcCode:output_type -> beacon.api.v1.GetNfcCodeResponse
	4,  // 11: beacon.api.v1.BeaconCommandService.AssignBeaconToClassroom:output_type -> beacon.api.v1.AssignBeaconToClassroomResponse
	6,  // 12: beacon.api.v1.BeaconCommandService.RemoveBeaconFromClassroom:output_type -> beacon.api.v1.RemoveBeaconFromClassroomResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_services_beacon_beacon_v1_beacon_proto_init() }
func file_services_beacon_beacon_v1_beacon_proto_init() {
	if File_services_beacon_beacon_v1_beacon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_beacon_beacon_v1_beacon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Beacon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_beacon_beacon_v1_beacon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBeaconsByClassroomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_beacon_beacon_v1_beacon_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBeaconsByClassroomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_beacon_beacon_v1_beacon_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssignBeaconToClassroomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_beacon_beacon_v1_beacon_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssignBeaconToClassroomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_beacon_beacon_v1_beacon_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveBeaconFromClassroomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_beacon_beacon_v1_beacon_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveBeaconFromClassroomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_beacon_beacon_v1_beacon_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateNfcCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_beacon_beacon_v1_beacon_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateNfcCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_beacon_beacon_v1_beacon_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateBuzzLightyearProofRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_beacon_beacon_v1_beacon_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateBuzzLightyearProofResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_beacon_beacon_v1_beacon_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNfcCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_beacon_beacon_v1_beacon_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNfcCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_beacon_beacon_v1_beacon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_services_beacon_beacon_v1_beacon_proto_goTypes,
		DependencyIndexes: file_services_beacon_beacon_v1_beacon_proto_depIdxs,
		MessageInfos:      file_services_beacon_beacon_v1_beacon_proto_msgTypes,
	}.Build()
	File_services_beacon_beacon_v1_beacon_proto = out.File
	file_services_beacon_beacon_v1_beacon_proto_rawDesc = nil
	file_services_beacon_beacon_v1_beacon_proto_goTypes = nil
	file_services_beacon_beacon_v1_beacon_proto_depIdxs = nil
}
