FROM golang:1.22 AS build

ARG SERVICE_DIR

WORKDIR /src

# Pre-cache dependencies.
COPY ${SERVICE_DIR}/go.mod ${SERVICE_DIR}/go.sum ./
RUN go mod download

COPY ${SERVICE_DIR} ./

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/server ./cmd/server

FROM gcr.io/distroless/static:nonroot

COPY --from=build /out/server /server

USER nonroot:nonroot

ENTRYPOINT ["/server"]
