// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.4
// source: services/auth-identity/identity/v1/identity.proto

package identityv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	IdentityQueryService_GetUserLite_FullMethodName           = "/identity.api.v1.IdentityQueryService/GetUserLite"
	IdentityQueryService_Exists_FullMethodName                = "/identity.api.v1.IdentityQueryService/Exists"
	IdentityQueryService_ValidateStudentDevice_FullMethodName = "/identity.api.v1.IdentityQueryService/ValidateStudentDevice"
	IdentityQueryService_ListUsersSummary_FullMethodName      = "/identity.api.v1.IdentityQueryService/ListUsersSummary"
)

// IdentityQueryServiceClient is the client API for IdentityQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdentityQueryServiceClient interface {
	GetUserLite(ctx context.Context, in *GetUserLiteRequest, opts ...grpc.CallOption) (*GetUserLiteResponse, error)
	Exists(ctx context.Context, in *ExistsRequest, opts ...grpc.CallOption) (*ExistsResponse, error)
	ValidateStudentDevice(ctx context.Context, in *ValidateStudentDeviceRequest, opts ...grpc.CallOption) (*ValidateStudentDeviceResponse, error)
	ListUsersSummary(ctx context.Context, in *ListUsersSummaryRequest, opts ...grpc.CallOption) (*ListUsersSummaryResponse, error)
}

type identityQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityQueryServiceClient(cc grpc.ClientConnInterface) IdentityQueryServiceClient {
	return &identityQueryServiceClient{cc}
}

func (c *identityQueryServiceClient) GetUserLite(ctx context.Context, in *GetUserLiteRequest, opts ...grpc.CallOption) (*GetUserLiteResponse, error) {
	out := new(GetUserLiteResponse)
	err := c.cc.Invoke(ctx, IdentityQueryService_GetUserLite_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityQueryServiceClient) Exists(ctx context.Context, in *ExistsRequest, opts ...grpc.CallOption) (*ExistsResponse, error) {
	out := new(ExistsResponse)
	err := c.cc.Invoke(ctx, IdentityQueryService_Exists_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityQueryServiceClient) ValidateStudentDevice(ctx context.Context, in *ValidateStudentDeviceRequest, opts ...grpc.CallOption) (*ValidateStudentDeviceResponse, error) {
	out := new(ValidateStudentDeviceResponse)
	err := c.cc.Invoke(ctx, IdentityQueryService_ValidateStudentDevice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityQueryServiceClient) ListUsersSummary(ctx context.Context, in *ListUsersSummaryRequest, opts ...grpc.CallOption) (*ListUsersSummaryResponse, error) {
	out := new(ListUsersSummaryResponse)
	err := c.cc.Invoke(ctx, IdentityQueryService_ListUsersSummary_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityQueryServiceServer is the server API for IdentityQueryService service.
// All implementations must embed UnimplementedIdentityQueryServiceServer
// for forward compatibility
type IdentityQueryServiceServer interface {
	GetUserLite(context.Context, *GetUserLiteRequest) (*GetUserLiteResponse, error)
	Exists(context.Context, *ExistsRequest) (*ExistsResponse, error)
	ValidateStudentDevice(context.Context, *ValidateStudentDeviceRequest) (*ValidateStudentDeviceResponse, error)
	ListUsersSummary(context.Context, *ListUsersSummaryRequest) (*ListUsersSummaryResponse, error)
	mustEmbedUnimplementedIdentityQueryServiceServer()
}

// UnimplementedIdentityQueryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIdentityQueryServiceServer struct {
}

func (UnimplementedIdentityQueryServiceServer) GetUserLite(context.Context, *GetUserLiteRequest) (*GetUserLiteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserLite not implemented")
}
func (UnimplementedIdentityQueryServiceServer) Exists(context.Context, *ExistsRequest) (*ExistsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Exists not implemented")
}
func (UnimplementedIdentityQueryServiceServer) ValidateStudentDevice(context.Context, *ValidateStudentDeviceRequest) (*ValidateStudentDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateStudentDevice not implemented")
}
func (UnimplementedIdentityQueryServiceServer) ListUsersSummary(context.Context, *ListUsersSummaryRequest) (*ListUsersSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsersSummary not implemented")
}
func (UnimplementedIdentityQueryServiceServer) mustEmbedUnimplementedIdentityQueryServiceServer() {}

// UnsafeIdentityQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityQueryServiceServer will
// result in compilation errors.
type UnsafeIdentityQueryServiceServer interface {
	mustEmbedUnimplementedIdentityQueryServiceServer()
}

func RegisterIdentityQueryServiceServer(s grpc.ServiceRegistrar, srv IdentityQueryServiceServer) {
	s.RegisterService(&IdentityQueryService_ServiceDesc, srv)
}

func _IdentityQueryService_GetUserLite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserLiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityQueryServiceServer).GetUserLite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityQueryService_GetUserLite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityQueryServiceServer).GetUserLite(ctx, req.(*GetUserLiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityQueryService_Exists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityQueryServiceServer).Exists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityQueryService_Exists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityQueryServiceServer).Exists(ctx, req.(*ExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityQueryService_ValidateStudentDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateStudentDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityQueryServiceServer).ValidateStudentDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityQueryService_ValidateStudentDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityQueryServiceServer).ValidateStudentDevice(ctx, req.(*ValidateStudentDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityQueryService_ListUsersSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityQueryServiceServer).ListUsersSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityQueryService_ListUsersSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityQueryServiceServer).ListUsersSummary(ctx, req.(*ListUsersSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityQueryService_ServiceDesc is the grpc.ServiceDesc for IdentityQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "identity.api.v1.IdentityQueryService",
	HandlerType: (*IdentityQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserLite",
			Handler:    _IdentityQueryService_GetUserLite_Handler,
		},
		{
			MethodName: "Exists",
			Handler:    _IdentityQueryService_Exists_Handler,
		},
		{
			MethodName: "ValidateStudentDevice",
			Handler:    _IdentityQueryService_ValidateStudentDevice_Handler,
		},
		{
			MethodName: "ListUsersSummary",
			Handler:    _IdentityQueryService_ListUsersSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/auth-identity/identity/v1/identity.proto",
}
