// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.1
// source: academics/v1/academics.proto

package academicsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AcademicsQueryService_GetCourse_FullMethodName               = "/academics.api.v1.AcademicsQueryService/GetCourse"
	AcademicsQueryService_ValidateTeacherCourse_FullMethodName   = "/academics.api.v1.AcademicsQueryService/ValidateTeacherCourse"
	AcademicsQueryService_ValidateStudentCourse_FullMethodName   = "/academics.api.v1.AcademicsQueryService/ValidateStudentCourse"
	AcademicsQueryService_ValidateClassroomCourse_FullMethodName = "/academics.api.v1.AcademicsQueryService/ValidateClassroomCourse"
)

// AcademicsQueryServiceClient is the client API for AcademicsQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AcademicsQueryServiceClient interface {
	GetCourse(ctx context.Context, in *GetCourseRequest, opts ...grpc.CallOption) (*GetCourseResponse, error)
	ValidateTeacherCourse(ctx context.Context, in *ValidateTeacherCourseRequest, opts ...grpc.CallOption) (*ValidateTeacherCourseResponse, error)
	ValidateStudentCourse(ctx context.Context, in *ValidateStudentCourseRequest, opts ...grpc.CallOption) (*ValidateStudentCourseResponse, error)
	ValidateClassroomCourse(ctx context.Context, in *ValidateClassroomCourseRequest, opts ...grpc.CallOption) (*ValidateClassroomCourseResponse, error)
}

type academicsQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAcademicsQueryServiceClient(cc grpc.ClientConnInterface) AcademicsQueryServiceClient {
	return &academicsQueryServiceClient{cc}
}

func (c *academicsQueryServiceClient) GetCourse(ctx context.Context, in *GetCourseRequest, opts ...grpc.CallOption) (*GetCourseResponse, error) {
	out := new(GetCourseResponse)
	err := c.cc.Invoke(ctx, AcademicsQueryService_GetCourse_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicsQueryServiceClient) ValidateTeacherCourse(ctx context.Context, in *ValidateTeacherCourseRequest, opts ...grpc.CallOption) (*ValidateTeacherCourseResponse, error) {
	out := new(ValidateTeacherCourseResponse)
	err := c.cc.Invoke(ctx, AcademicsQueryService_ValidateTeacherCourse_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicsQueryServiceClient) ValidateStudentCourse(ctx context.Context, in *ValidateStudentCourseRequest, opts ...grpc.CallOption) (*ValidateStudentCourseResponse, error) {
	out := new(ValidateStudentCourseResponse)
	err := c.cc.Invoke(ctx, AcademicsQueryService_ValidateStudentCourse_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicsQueryServiceClient) ValidateClassroomCourse(ctx context.Context, in *ValidateClassroomCourseRequest, opts ...grpc.CallOption) (*ValidateClassroomCourseResponse, error) {
	out := new(ValidateClassroomCourseResponse)
	err := c.cc.Invoke(ctx, AcademicsQueryService_ValidateClassroomCourse_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AcademicsQueryServiceServer is the server API for AcademicsQueryService service.
// All implementations must embed UnimplementedAcademicsQueryServiceServer
// for forward compatibility
type AcademicsQueryServiceServer interface {
	GetCourse(context.Context, *GetCourseRequest) (*GetCourseResponse, error)
	ValidateTeacherCourse(context.Context, *ValidateTeacherCourseRequest) (*ValidateTeacherCourseResponse, error)
	ValidateStudentCourse(context.Context, *ValidateStudentCourseRequest) (*ValidateStudentCourseResponse, error)
	ValidateClassroomCourse(context.Context, *ValidateClassroomCourseRequest) (*ValidateClassroomCourseResponse, error)
	mustEmbedUnimplementedAcademicsQueryServiceServer()
}

// UnimplementedAcademicsQueryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAcademicsQueryServiceServer struct {
}

func (UnimplementedAcademicsQueryServiceServer) GetCourse(context.Context, *GetCourseRequest) (*GetCourseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCourse not implemented")
}
func (UnimplementedAcademicsQueryServiceServer) ValidateTeacherCourse(context.Context, *ValidateTeacherCourseRequest) (*ValidateTeacherCourseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateTeacherCourse not implemented")
}
func (UnimplementedAcademicsQueryServiceServer) ValidateStudentCourse(context.Context, *ValidateStudentCourseRequest) (*ValidateStudentCourseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateStudentCourse not implemented")
}
func (UnimplementedAcademicsQueryServiceServer) ValidateClassroomCourse(context.Context, *ValidateClassroomCourseRequest) (*ValidateClassroomCourseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateClassroomCourse not implemented")
}
func (UnimplementedAcademicsQueryServiceServer) mustEmbedUnimplementedAcademicsQueryServiceServer() {}

// UnsafeAcademicsQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AcademicsQueryServiceServer will
// result in compilation errors.
type UnsafeAcademicsQueryServiceServer interface {
	mustEmbedUnimplementedAcademicsQueryServiceServer()
}

func RegisterAcademicsQueryServiceServer(s grpc.ServiceRegistrar, srv AcademicsQueryServiceServer) {
	s.RegisterService(&AcademicsQueryService_ServiceDesc, srv)
}

func _AcademicsQueryService_GetCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicsQueryServiceServer).GetCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcademicsQueryService_GetCourse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicsQueryServiceServer).GetCourse(ctx, req.(*GetCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicsQueryService_ValidateTeacherCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTeacherCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicsQueryServiceServer).ValidateTeacherCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcademicsQueryService_ValidateTeacherCourse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicsQueryServiceServer).ValidateTeacherCourse(ctx, req.(*ValidateTeacherCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicsQueryService_ValidateStudentCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateStudentCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicsQueryServiceServer).ValidateStudentCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcademicsQueryService_ValidateStudentCourse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicsQueryServiceServer).ValidateStudentCourse(ctx, req.(*ValidateStudentCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicsQueryService_ValidateClassroomCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateClassroomCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicsQueryServiceServer).ValidateClassroomCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcademicsQueryService_ValidateClassroomCourse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicsQueryServiceServer).ValidateClassroomCourse(ctx, req.(*ValidateClassroomCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AcademicsQueryService_ServiceDesc is the grpc.ServiceDesc for AcademicsQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AcademicsQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "academics.api.v1.AcademicsQueryService",
	HandlerType: (*AcademicsQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCourse",
			Handler:    _AcademicsQueryService_GetCourse_Handler,
		},
		{
			MethodName: "ValidateTeacherCourse",
			Handler:    _AcademicsQueryService_ValidateTeacherCourse_Handler,
		},
		{
			MethodName: "ValidateStudentCourse",
			Handler:    _AcademicsQueryService_ValidateStudentCourse_Handler,
		},
		{
			MethodName: "ValidateClassroomCourse",
			Handler:    _AcademicsQueryService_ValidateClassroomCourse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "academics/v1/academics.proto",
}
