// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idempotency.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBeaconIdempotency = `-- name: CreateBeaconIdempotency :exec
INSERT INTO beacon_idempotency_keys (
  id,
  beacon_id,
  key,
  endpoint,
  response_status,
  response_body,
  created_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
`

type CreateBeaconIdempotencyParams struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	BeaconID       pgtype.UUID        `db:"beacon_id" json:"beacon_id"`
	Key            string             `db:"key" json:"key"`
	Endpoint       string             `db:"endpoint" json:"endpoint"`
	ResponseStatus int32              `db:"response_status" json:"response_status"`
	ResponseBody   pgtype.Text        `db:"response_body" json:"response_body"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateBeaconIdempotency(ctx context.Context, arg CreateBeaconIdempotencyParams) error {
	_, err := q.db.Exec(ctx, createBeaconIdempotency,
		arg.ID,
		arg.BeaconID,
		arg.Key,
		arg.Endpoint,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.CreatedAt,
	)
	return err
}

const getBeaconIdempotency = `-- name: GetBeaconIdempotency :one
SELECT id, beacon_id, key, endpoint, response_status, response_body, created_at
FROM beacon_idempotency_keys
WHERE beacon_id = $1 AND key = $2 AND endpoint = $3
`

type GetBeaconIdempotencyParams struct {
	BeaconID pgtype.UUID `db:"beacon_id" json:"beacon_id"`
	Key      string      `db:"key" json:"key"`
	Endpoint string      `db:"endpoint" json:"endpoint"`
}

func (q *Queries) GetBeaconIdempotency(ctx context.Context, arg GetBeaconIdempotencyParams) (BeaconIdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getBeaconIdempotency, arg.BeaconID, arg.Key, arg.Endpoint)
	var i BeaconIdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.BeaconID,
		&i.Key,
		&i.Endpoint,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}
