// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBeaconToken = `-- name: CreateBeaconToken :one
INSERT INTO beacon_tokens (
  id,
  beacon_id,
  token_hash,
  refresh_token_hash,
  created_at,
  expires_at,
  refresh_expires_at,
  revoked_at,
  last_used_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, beacon_id, token_hash, refresh_token_hash, created_at, expires_at, refresh_expires_at, revoked_at, last_used_at
`

type CreateBeaconTokenParams struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	BeaconID         pgtype.UUID        `db:"beacon_id" json:"beacon_id"`
	TokenHash        string             `db:"token_hash" json:"token_hash"`
	RefreshTokenHash string             `db:"refresh_token_hash" json:"refresh_token_hash"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt        pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RefreshExpiresAt pgtype.Timestamptz `db:"refresh_expires_at" json:"refresh_expires_at"`
	RevokedAt        pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	LastUsedAt       pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
}

func (q *Queries) CreateBeaconToken(ctx context.Context, arg CreateBeaconTokenParams) (BeaconToken, error) {
	row := q.db.QueryRow(ctx, createBeaconToken,
		arg.ID,
		arg.BeaconID,
		arg.TokenHash,
		arg.RefreshTokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.RefreshExpiresAt,
		arg.RevokedAt,
		arg.LastUsedAt,
	)
	var i BeaconToken
	err := row.Scan(
		&i.ID,
		&i.BeaconID,
		&i.TokenHash,
		&i.RefreshTokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RefreshExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getBeaconTokenByHash = `-- name: GetBeaconTokenByHash :one
SELECT id, beacon_id, token_hash, refresh_token_hash, created_at, expires_at, refresh_expires_at, revoked_at, last_used_at
FROM beacon_tokens
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetBeaconTokenByHash(ctx context.Context, tokenHash string) (BeaconToken, error) {
	row := q.db.QueryRow(ctx, getBeaconTokenByHash, tokenHash)
	var i BeaconToken
	err := row.Scan(
		&i.ID,
		&i.BeaconID,
		&i.TokenHash,
		&i.RefreshTokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RefreshExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getBeaconTokenByRefresh = `-- name: GetBeaconTokenByRefresh :one
SELECT id, beacon_id, token_hash, refresh_token_hash, created_at, expires_at, refresh_expires_at, revoked_at, last_used_at
FROM beacon_tokens
WHERE refresh_token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetBeaconTokenByRefresh(ctx context.Context, refreshTokenHash string) (BeaconToken, error) {
	row := q.db.QueryRow(ctx, getBeaconTokenByRefresh, refreshTokenHash)
	var i BeaconToken
	err := row.Scan(
		&i.ID,
		&i.BeaconID,
		&i.TokenHash,
		&i.RefreshTokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RefreshExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const revokeBeaconToken = `-- name: RevokeBeaconToken :exec
UPDATE beacon_tokens
SET revoked_at = $2
WHERE id = $1 AND revoked_at IS NULL
`

type RevokeBeaconTokenParams struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	RevokedAt pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

func (q *Queries) RevokeBeaconToken(ctx context.Context, arg RevokeBeaconTokenParams) error {
	_, err := q.db.Exec(ctx, revokeBeaconToken, arg.ID, arg.RevokedAt)
	return err
}

const touchBeaconToken = `-- name: TouchBeaconToken :exec
UPDATE beacon_tokens
SET last_used_at = $2
WHERE id = $1
`

type TouchBeaconTokenParams struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	LastUsedAt pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
}

func (q *Queries) TouchBeaconToken(ctx context.Context, arg TouchBeaconTokenParams) error {
	_, err := q.db.Exec(ctx, touchBeaconToken, arg.ID, arg.LastUsedAt)
	return err
}
