// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Classroom struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	SchoolID  pgtype.UUID        `db:"school_id" json:"school_id"`
	Name      string             `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type Course struct {
	ID                           pgtype.UUID        `db:"id" json:"id"`
	SchoolID                     pgtype.UUID        `db:"school_id" json:"school_id"`
	Name                         string             `db:"name" json:"name"`
	StartAt                      pgtype.Timestamptz `db:"start_at" json:"start_at"`
	EndAt                        pgtype.Timestamptz `db:"end_at" json:"end_at"`
	IsOnline                     bool               `db:"is_online" json:"is_online"`
	SignatureClosingDelayMinutes int32              `db:"signature_closing_delay_minutes" json:"signature_closing_delay_minutes"`
	SignatureClosed              bool               `db:"signature_closed" json:"signature_closed"`
	CreatedAt                    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt                    pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type CoursesClassroom struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	CourseID    pgtype.UUID        `db:"course_id" json:"course_id"`
	ClassroomID pgtype.UUID        `db:"classroom_id" json:"classroom_id"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type CoursesStudentGroup struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	CourseID       pgtype.UUID        `db:"course_id" json:"course_id"`
	StudentGroupID pgtype.UUID        `db:"student_group_id" json:"student_group_id"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type School struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	Name          string             `db:"name" json:"name"`
	PreferencesID pgtype.UUID        `db:"preferences_id" json:"preferences_id"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type SchoolPreference struct {
	ID                                  pgtype.UUID        `db:"id" json:"id"`
	DefaultSignatureClosingDelayMinutes int32              `db:"default_signature_closing_delay_minutes" json:"default_signature_closing_delay_minutes"`
	TeacherCanModifyClosingDelay        bool               `db:"teacher_can_modify_closing_delay" json:"teacher_can_modify_closing_delay"`
	StudentsCanSignBeforeTeacher        bool               `db:"students_can_sign_before_teacher" json:"students_can_sign_before_teacher"`
	EnableFlash                         bool               `db:"enable_flash" json:"enable_flash"`
	EnableQrcode                        bool               `db:"enable_qrcode" json:"enable_qrcode"`
	EnableNfc                           bool               `db:"enable_nfc" json:"enable_nfc"`
	CreatedAt                           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt                           pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type StudentGroup struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	SchoolID           pgtype.UUID        `db:"school_id" json:"school_id"`
	Name               string             `db:"name" json:"name"`
	SingleStudentGroup bool               `db:"single_student_group" json:"single_student_group"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type StudentsGroup struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	StudentID      pgtype.UUID        `db:"student_id" json:"student_id"`
	StudentGroupID pgtype.UUID        `db:"student_group_id" json:"student_group_id"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type TeachersCourse struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	TeacherID pgtype.UUID        `db:"teacher_id" json:"teacher_id"`
	CourseID  pgtype.UUID        `db:"course_id" json:"course_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
